version: "3.8"
services:
  app:
    build: .
    container_name: django_app
    env_file:
      - .env
    entrypoint: ['uwsgi', '--socket', ':8000', '--module', "${WSGI_APPLICATION_NAME}"]
    restart: always
    ports:
      - "8000:8000"
      - "80:80"